version: '2'
services:
  zookeeper:
    image: hyperledger/fabric-zookeeper:0.4.10
    ports:
      - "2181:2181"
  kafka0:
    image: hyperledger/fabric-kafka:0.4.10
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
#      - KAFKA_NUM_REPLICA_FETCHERS=1
#      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ADVERTIZED_HOST_NAME=hyperledger3
#      - KAFKA_ADVERTIZED_PORT=9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
